version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    hostname: memes
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: memes
    volumes:
      - memes_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  minio:
    image: minio/minio:latest
    hostname: minio
    env_file:
      - .env.dev
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always


  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - posts

  posts:
    build:
      context: .
      dockerfile: app/posts/Dockerfile
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn app.posts.main:app --host 0.0.0.0 --port 8001"
    hostname: posts
    restart: always
    shm_size: 128mb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/check_health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8001:8001"
    depends_on:
      - db
      - minio
    env_file:
      - .env.dev

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/posts/openapi.json:/etc/nginx/html/posts/openapi.json
    depends_on:
      - posts

volumes:
  memes_data:
    driver: local
  minio_data:
    driver: local
  rabbit-data:
    driver: local
  s3_data:
    driver: local
