version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    hostname: memes
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: memes
    volumes:
      - memes_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - s3-media

  minio:
    image: minio/minio:latest
    hostname: minio
    env_file:
      - .env.dev
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always
    networks:
      - s3-media

  frontend:
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - posts
    networks:
      - s3-media

  posts:
    build:
      context: .
      dockerfile: ./app/posts/Dockerfile
    hostname: posts
    restart: always
    shm_size: 128mb
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env.dev
    networks:
      - s3-media


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/posts/openapi.json:/etc/nginx/html/posts/openapi.json
    depends_on:
      - posts
    networks:
      - s3-media


networks:
  s3-media:
    driver: bridge

volumes:
  memes_data:
    driver: local
  minio_data:
    driver: local
  rabbit-data:
    driver: local
  s3_data:
    driver: local
