version: '3'
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    shm_size: 128mb
    hostname: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - memes_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.postgres.dev

volumes:
  memes_data:
    driver: local